# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "outcome", # <defog_npi>
  "outcome", # <defog_npi_wide>
  "data_lists", # <defog_npi_wide>
  "id", # <defog_npi_wide>
  "prov_type", # <defog_npi_wide>
  "npi", # <defog_npi_wide>
  "enumeration_type", # <defog_npi_wide>
  "number", # <defog_npi_wide>
  "basic", # <defog_npi_wide>
  "value", # <defog_npi_wide>
  "country_code", # <defog_npi_wide>
  "state", # <defog_npi_wide>
  "allowed_amounts", # <defog_oon>
  "service_code", # <defog_oon>
  "payments", # <defog_oon>
  "providers", # <defog_oon>
  "tin", # <defog_oon>
  "value", # <defog_oon>
  "type", # <defog_oon>
  "npi", # <defog_oon>
  "npi_no", # <defog_oon>
  "in_network_files", # <defog_toc>
  "location", # <defog_toc>
  "allowed_amount_file", # <defog_toc>
  "reporting_plans", # <defog_toc>
  "in_network", # <defog_toc>
  "out_of_network", # <defog_toc>
  "location", # <defog_toc_centene>
  "state", # <defog_toc_centene>
  "sub_entity", # <defog_toc_centene>
  "id", # <defog_toc_centene>
  "entity", # <defog_toc_centene>
  NULL
))
